# Project information
site_name: Programming 101
site_url: https://code.sbamin.com
site_author: "Samir B. Amin"
site_description: >-
  Notes on programming for computational biology: Using R, bash, and python on HPC.

# Repository
repo_name: sbamin/code101
repo_url: https://github.com/sbamin/code101
edit_uri: "edit/scratch/web/docs/"

# Copyright
copyright: >-
  <a href="/disclosure/">Disclosure</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/fixed/sitelogo.png

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
  palette: #
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate # 
      primary: teal
      accent: "light green"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Fira Code'
  icon:
    logo: logo
    repo: material/github
    edit: material/pencil
    view: material/eye
  favicon: assets/images/fixed/favicon.ico

# Plugins
plugins:
  - search
  - macros
  - git-revision-date-localized:
      type: timeago
      timezone: 'America/New_York'
      fallback_to_build_date: true
      ## enabling creation date will impact peformance
      enable_creation_date: false
  - minify:
      minify_html: true
  - git-authors:
      show_contribution: false
      show_line_count: false
      show_email_address: false
      count_empty_lines: false
      fallback_to_empty: false
      sort_authors_by: name
      authorship_threshold_percent: 10
      exclude:
          - index.md
      enabled: true
  - tags:
      tags_file: tags.md
  - blog:
      blog_toc: true
      authors: true
      draft_on_serve: true
      draft_if_future_date: true
      post_date_format: medium
      post_url_date_format: yyyy
      post_url_format: "{date}/{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_excerpt: optional
      archive_toc: true

## Customization
extra_css:
  - assets/css/extra.css

extra_javascript:
  - 'assets/js/extra.js'
  - 'assets/js/mathjax.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js'
  - 'assets/js/tables.js'

extra:
  disqus: ''
  twitter: 'sbamin'
  social:
    - icon: octicons/person-16
      link: https://sbamin.com/about
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sbamin
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/samiramin/
    - icon: fontawesome/brands/github
      link: https://github.com/sbamin
    - icon: fontawesome/regular/envelope
      link: https://sbamin.com/contact
  repo:
    url: https://github.com/sbamin/code101
    base: sbamin/code101
    tree: /tree/main
    blob: /blob/main
    raw: /raw/scratch/web/docs
    viewfile: /blob/scratch/web/docs
    viewdir: /tree/scratch/web/docs
  analytics:
    provider: google
    property: UA-307297-1
  site_keywords: "linux,getting started,computing,hpc, conda,bash,jupyter,programming,biology,bioinformatics,gpu"
  sitebuilder:
    url: https://github.com/sbamin/sitebuilder/releases
    release: "1.5.2b1_arm64"
  version:
    provider: mike
    default: latest
  comments:
    enabled: true
    # defaults to utterances unless replaced mode: giscus
    mode: utterances
    type: issues

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      title: "On this page"
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      social_url_shortener: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: sbamin
      repo: code101
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - Getting started with HPC:
    - hpc/index.md
    - CPU Computing:
      - Part 1: hpc/cpu/sumner_1.md
      - Part 2: hpc/cpu/sumner_2.md
      - Part 3: hpc/cpu/sumner_3.md
    - GPU Computing:
      - GPU setup: hpc/gpu/winter_1.md
      - Image analysis on GPU-based HPC: hpc/gpu/image_analysis_cellprofiler_cellpose.md
  - Tags: tags.md

#_end_
